[k3s-master]
k3s-01 ansible_host=192.168.1.10 ansible_user=ubuntu

[k3s-agent]
k3s-02 ansible_host=192.168.1.11 ansible_user=ubuntu
k3s-03 ansible_host=192.168.1.12 ansible_user=ubuntu

[k3s:children]
k3s-master
k3s-agent

[all:vars]
ansible_python_interpreter=/usr/bin/python3
